name: Tests
# https://github.com/shivammathur/setup-php
on:
  push:
  pull_request:
    branches-ignore: [ main ]

env:
  extensions: :opcache #intl, pcov #fileinfo is needed for Windows

jobs:
  tests:    
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    runs-on: ubuntu-latest
    container:
      image: gitlab.zataca.es:5050/operaciones/contenedores/php81:1.0.0
      credentials:
            username: gitlab-imagenes
            password: ${{ secrets.GITLAB_REGISTRO_DE_IMAGENES }}
    strategy:
      fail-fast: false
    services:
      postgres:
        image: gitlab.zataca.es:5050/operaciones/contenedores/postgres12:0.0.2
        credentials:
            username: gitlab-imagenes
            password: ${{ secrets.GITLAB_REGISTRO_DE_IMAGENES }}
        env:
          POSTGRES_DB: tests
          POSTGRES_USER: zataca
          POSTGRES_PASSWORD: zataca
          POSTGRES_HOST_AUTH_METHOD: md5 
        # Set health checks to wait until postgres has started
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Checkout
      uses: actions/checkout@v3
  
    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"
        ls
        echo ${{ steps.composer-cache.outputs.dir }}

    - uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Composer Install
      run: php composer.phar install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Permisos en carpetas
      run: chmod -R 777 storage bootstrap/cache
  
    - name: Migraciones y Seeders
      run: php artisan migrate --seed --env=testing

    - name: Phpunit
      run: vendor/bin/phpunit
